<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NFbnRGAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NFbnRGA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NFbnRGA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dev' => ['privates', 'security.firewall.map.config.dev', 'getSecurity_Firewall_Map_Config_DevService', true],
            'api_public' => ['privates', 'security.firewall.map.config.api_public', 'getSecurity_Firewall_Map_Config_ApiPublicService', true],
            'api_login' => ['privates', 'security.firewall.map.config.api_login', 'getSecurity_Firewall_Map_Config_ApiLoginService', true],
            'api_forgot' => ['privates', 'security.firewall.map.config.api_forgot', 'getSecurity_Firewall_Map_Config_ApiForgotService', true],
            'api_refresh' => ['privates', 'security.firewall.map.config.api_refresh', 'getSecurity_Firewall_Map_Config_ApiRefreshService', true],
            'api' => ['privates', 'security.firewall.map.config.api', 'getSecurity_Firewall_Map_Config_ApiService', true],
        ], [
            'dev' => '?',
            'api_public' => '?',
            'api_login' => '?',
            'api_forgot' => '?',
            'api_refresh' => '?',
            'api' => '?',
        ]);
    }
}
