<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgentManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Manager\Business\AgentManager' shared autowired service.
     *
     * @return \App\Manager\Business\AgentManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Manager/Business/AgentManager.php';

        return $container->privates['App\\Manager\\Business\\AgentManager'] = new \App\Manager\Business\AgentManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\Business\\AgentRepository'] ?? $container->load('getAgentRepositoryService')), ($container->privates['App\\Repository\\Admin\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\CompanyRepository'] ?? $container->load('getCompanyRepository2Service')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->privates['App\\Repository\\Extra\\UserOtpRepository'] ?? $container->load('getUserOtpRepositoryService')), ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')), ($container->privates['App\\Service\\NotificationService'] ?? $container->load('getNotificationServiceService')), ($container->privates['App\\Repository\\Extra\\NotificationRepository'] ?? $container->load('getNotificationRepositoryService')));
    }
}
