<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Business\AgentController' shared autowired service.
     *
     * @return \App\Controller\Business\AgentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Business/AgentController.php';

        $instance = new \App\Controller\Business\AgentController(($container->privates['App\\Repository\\Business\\AgentRepository'] ?? $container->load('getAgentRepositoryService')), ($container->privates['App\\Manager\\Business\\AgentManager'] ?? $container->load('getAgentManagerService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Business\\AgentController', $container));

        return $container->services['App\\Controller\\Business\\AgentController'] = $instance;
    }
}
