<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompanyInvoiceControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Business\CompanyInvoiceController' shared autowired service.
     *
     * @return \App\Controller\Business\CompanyInvoiceController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Business/CompanyInvoiceController.php';
        include_once \dirname(__DIR__, 4).'/src/Manager/Business/CompanyInvoiceManager.php';

        $instance = new \App\Controller\Business\CompanyInvoiceController(new \App\Manager\Business\CompanyInvoiceManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\Business\\CompanyInvoiceRepository'] ?? $container->load('getCompanyInvoiceRepositoryService')), ($container->privates['App\\Repository\\Business\\CompanyRepository'] ?? $container->load('getCompanyRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Business\\CompanyInvoiceController', $container));

        return $container->services['App\\Controller\\Business\\CompanyInvoiceController'] = $instance;
    }
}
