<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandPath_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CommandPath.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CommandPath.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('z:g:path', [], 'Generate path routes for Passe Voyage', false, #[\Closure(name: 'App\\Command\\CommandPath')] fn (): \App\Command\CommandPath => ($container->privates['App\\Command\\CommandPath'] ?? $container->load('getCommandPathService')));
    }
}
