<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompanyFundControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Business\CompanyFundController' shared autowired service.
     *
     * @return \App\Controller\Business\CompanyFundController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Business/CompanyFundController.php';
        include_once \dirname(__DIR__, 4).'/src/Manager/Business/CompanyFundManager.php';

        $a = ($container->privates['App\\Repository\\Business\\CompanyFundRepository'] ?? $container->load('getCompanyFundRepositoryService'));
        $b = ($container->privates['App\\Repository\\Business\\CompanyRepository'] ?? $container->load('getCompanyRepositoryService'));
        $c = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        $instance = new \App\Controller\Business\CompanyFundController($a, $b, new \App\Manager\Business\CompanyFundManager($c, $a, $b), $c);

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Business\\CompanyFundController', $container));

        return $container->services['App\\Controller\\Business\\CompanyFundController'] = $instance;
    }
}
