<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreditPolicyControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Business\CreditPolicyController' shared autowired service.
     *
     * @return \App\Controller\Business\CreditPolicyController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Business/CreditPolicyController.php';
        include_once \dirname(__DIR__, 4).'/src/Manager/Business/CreditPolicyManager.php';

        $instance = new \App\Controller\Business\CreditPolicyController(new \App\Manager\Business\CreditPolicyManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\Business\\CreditPolicyRepository'] ?? $container->load('getCreditPolicyRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Business\\CreditPolicyController', $container));

        return $container->services['App\\Controller\\Business\\CreditPolicyController'] = $instance;
    }
}
