<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Orm_DefaultConfigurationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'doctrine.orm.default_configuration' shared service.
     *
     * @return \Doctrine\ORM\Configuration
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/dbal/src/Configuration.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Configuration.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Mapping/Driver/MappingDriver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Mapping/MappingDriver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Mapping/Driver/MappingDriverChain.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/NamingStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/UnderscoreNamingStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/QuoteStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Internal/SQLResultCasing.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/DefaultQuoteStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/TypedFieldMapper.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/DefaultTypedFieldMapper.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/EntityListenerResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Mapping/EntityListenerServiceResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Mapping/ContainerEntityListenerResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Repository/RepositoryFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/RepositoryFactoryCompatibility.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ContainerRepositoryFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Mapping/Driver/ColocatedMappingDriver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/Driver/ReflectionBasedDriver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/Driver/AttributeDriver.php';

        $instance = new \Doctrine\ORM\Configuration();

        $a = new \Doctrine\Persistence\Mapping\Driver\MappingDriverChain();
        $a->addDriver(($container->privates['doctrine.orm.default_attribute_metadata_driver'] ??= new \Doctrine\ORM\Mapping\Driver\AttributeDriver([(\dirname(__DIR__, 4).'/src/Entity')], true)), 'App\\Entity');

        $instance->setEntityNamespaces(['App' => 'App\\Entity']);
        $instance->setMetadataCache(new \Symfony\Component\Cache\Adapter\ArrayAdapter());
        $instance->setQueryCache(($container->privates['cache.doctrine.orm.default.query'] ??= new \Symfony\Component\Cache\Adapter\ArrayAdapter()));
        $instance->setResultCache(($container->privates['cache.doctrine.orm.default.result'] ??= new \Symfony\Component\Cache\Adapter\ArrayAdapter()));
        $instance->setMetadataDriverImpl(new \Doctrine\Bundle\DoctrineBundle\Mapping\MappingDriver($a, new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine.ulid_generator' => ['privates', 'doctrine.ulid_generator', 'getDoctrine_UlidGeneratorService', true],
            'doctrine.uuid_generator' => ['privates', 'doctrine.uuid_generator', 'getDoctrine_UuidGeneratorService', true],
        ], [
            'doctrine.ulid_generator' => '?',
            'doctrine.uuid_generator' => '?',
        ])));
        $instance->setProxyDir(($container->targetDir.''.'/doctrine/orm/Proxies'));
        $instance->setProxyNamespace('Proxies');
        $instance->setAutoGenerateProxyClasses(true);
        $instance->setSchemaIgnoreClasses([]);
        $instance->setClassMetadataFactoryName('Doctrine\\Bundle\\DoctrineBundle\\Mapping\\ClassMetadataFactory');
        $instance->setDefaultRepositoryClassName('Doctrine\\ORM\\EntityRepository');
        $instance->setNamingStrategy(new \Doctrine\ORM\Mapping\UnderscoreNamingStrategy(0, true));
        $instance->setQuoteStrategy(new \Doctrine\ORM\Mapping\DefaultQuoteStrategy());
        $instance->setTypedFieldMapper(new \Doctrine\ORM\Mapping\DefaultTypedFieldMapper());
        $instance->setEntityListenerResolver(new \Doctrine\Bundle\DoctrineBundle\Mapping\ContainerEntityListenerResolver($container));
        $instance->setLazyGhostObjectEnabled(true);
        $instance->setIdentityGenerationPreferences(['Doctrine\\DBAL\\Platforms\\PostgreSQLPlatform' => 4]);
        $instance->setRepositoryFactory(new \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Repository\\Admin\\AdminRepository' => ['privates', 'App\\Repository\\Admin\\AdminRepository', 'getAdminRepositoryService', true],
            'App\\Repository\\Admin\\AuditLogRepository' => ['privates', 'App\\Repository\\Admin\\AuditLogRepository', 'getAuditLogRepositoryService', true],
            'App\\Repository\\Admin\\UserRepository' => ['privates', 'App\\Repository\\Admin\\UserRepository', 'getUserRepositoryService', true],
            'App\\Repository\\Business\\AgentRepository' => ['privates', 'App\\Repository\\Business\\AgentRepository', 'getAgentRepositoryService', true],
            'App\\Repository\\Business\\CityRepository' => ['privates', 'App\\Repository\\Business\\CityRepository', 'getCityRepositoryService', true],
            'App\\Repository\\Business\\CompanyFundRepository' => ['privates', 'App\\Repository\\Business\\CompanyFundRepository', 'getCompanyFundRepositoryService', true],
            'App\\Repository\\Business\\CompanyInvoiceRepository' => ['privates', 'App\\Repository\\Business\\CompanyInvoiceRepository', 'getCompanyInvoiceRepositoryService', true],
            'App\\Repository\\Business\\CompanyRepository' => ['privates', 'App\\Repository\\Business\\CompanyRepository', 'getCompanyRepositoryService', true],
            'App\\Repository\\Business\\CreditPolicyRepository' => ['privates', 'App\\Repository\\Business\\CreditPolicyRepository', 'getCreditPolicyRepositoryService', true],
            'App\\Repository\\Business\\CreditRepository' => ['privates', 'App\\Repository\\Business\\CreditRepository', 'getCreditRepositoryService', true],
            'App\\Repository\\Business\\CreditRequestRepository' => ['privates', 'App\\Repository\\Business\\CreditRequestRepository', 'getCreditRequestRepository2Service', true],
            'App\\Repository\\Business\\PassengerContactRepository' => ['privates', 'App\\Repository\\Business\\PassengerContactRepository', 'getPassengerContactRepositoryService', true],
            'App\\Repository\\Business\\PassengerRepository' => ['privates', 'App\\Repository\\Business\\PassengerRepository', 'getPassengerRepositoryService', true],
            'App\\Repository\\Business\\PaymentRepository' => ['privates', 'App\\Repository\\Business\\PaymentRepository', 'getPaymentRepositoryService', true],
            'App\\Repository\\Business\\RouteRepository' => ['privates', 'App\\Repository\\Business\\RouteRepository', 'getRouteRepositoryService', true],
            'App\\Repository\\Business\\StationRepository' => ['privates', 'App\\Repository\\Business\\StationRepository', 'getStationRepositoryService', true],
            'App\\Repository\\Business\\TariffRepository' => ['privates', 'App\\Repository\\Business\\TariffRepository', 'getTariffRepositoryService', true],
            'App\\Repository\\Business\\TicketRepository' => ['privates', 'App\\Repository\\Business\\TicketRepository', 'getTicketRepositoryService', true],
            'App\\Repository\\CompanyRepository' => ['privates', 'App\\Repository\\CompanyRepository', 'getCompanyRepository2Service', true],
            'App\\Repository\\CreditRepository' => ['privates', 'App\\Repository\\CreditRepository', 'getCreditRepository2Service', true],
            'App\\Repository\\CreditRequestRepository' => ['privates', 'App\\Repository\\CreditRequestRepository', 'getCreditRequestRepositoryService', true],
            'App\\Repository\\Extra\\AppRatingRepository' => ['privates', 'App\\Repository\\Extra\\AppRatingRepository', 'getAppRatingRepositoryService', true],
            'App\\Repository\\Extra\\FileRepository' => ['privates', 'App\\Repository\\Extra\\FileRepository', 'getFileRepositoryService', true],
            'App\\Repository\\Extra\\FolderRepository' => ['privates', 'App\\Repository\\Extra\\FolderRepository', 'getFolderRepositoryService', true],
            'App\\Repository\\Extra\\GeneralSettingHistoryRepository' => ['privates', 'App\\Repository\\Extra\\GeneralSettingHistoryRepository', 'getGeneralSettingHistoryRepositoryService', true],
            'App\\Repository\\Extra\\GeneralSettingRepository' => ['privates', 'App\\Repository\\Extra\\GeneralSettingRepository', 'getGeneralSettingRepositoryService', true],
            'App\\Repository\\Extra\\NotificationRepository' => ['privates', 'App\\Repository\\Extra\\NotificationRepository', 'getNotificationRepositoryService', true],
            'App\\Repository\\Extra\\NotificationSettingRepository' => ['privates', 'App\\Repository\\Extra\\NotificationSettingRepository', 'getNotificationSettingRepositoryService', true],
            'App\\Repository\\Extra\\PathRepository' => ['privates', 'App\\Repository\\Extra\\PathRepository', 'getPathRepositoryService', true],
            'App\\Repository\\Extra\\RefreshTokenRepository' => ['privates', 'App\\Repository\\Extra\\RefreshTokenRepository', 'getRefreshTokenRepositoryService', true],
            'App\\Repository\\Extra\\RoleRepository' => ['privates', 'App\\Repository\\Extra\\RoleRepository', 'getRoleRepositoryService', true],
            'App\\Repository\\Extra\\UserOtpRepository' => ['privates', 'App\\Repository\\Extra\\UserOtpRepository', 'getUserOtpRepositoryService', true],
        ], [
            'App\\Repository\\Admin\\AdminRepository' => '?',
            'App\\Repository\\Admin\\AuditLogRepository' => '?',
            'App\\Repository\\Admin\\UserRepository' => '?',
            'App\\Repository\\Business\\AgentRepository' => '?',
            'App\\Repository\\Business\\CityRepository' => '?',
            'App\\Repository\\Business\\CompanyFundRepository' => '?',
            'App\\Repository\\Business\\CompanyInvoiceRepository' => '?',
            'App\\Repository\\Business\\CompanyRepository' => '?',
            'App\\Repository\\Business\\CreditPolicyRepository' => '?',
            'App\\Repository\\Business\\CreditRepository' => '?',
            'App\\Repository\\Business\\CreditRequestRepository' => '?',
            'App\\Repository\\Business\\PassengerContactRepository' => '?',
            'App\\Repository\\Business\\PassengerRepository' => '?',
            'App\\Repository\\Business\\PaymentRepository' => '?',
            'App\\Repository\\Business\\RouteRepository' => '?',
            'App\\Repository\\Business\\StationRepository' => '?',
            'App\\Repository\\Business\\TariffRepository' => '?',
            'App\\Repository\\Business\\TicketRepository' => '?',
            'App\\Repository\\CompanyRepository' => '?',
            'App\\Repository\\CreditRepository' => '?',
            'App\\Repository\\CreditRequestRepository' => '?',
            'App\\Repository\\Extra\\AppRatingRepository' => '?',
            'App\\Repository\\Extra\\FileRepository' => '?',
            'App\\Repository\\Extra\\FolderRepository' => '?',
            'App\\Repository\\Extra\\GeneralSettingHistoryRepository' => '?',
            'App\\Repository\\Extra\\GeneralSettingRepository' => '?',
            'App\\Repository\\Extra\\NotificationRepository' => '?',
            'App\\Repository\\Extra\\NotificationSettingRepository' => '?',
            'App\\Repository\\Extra\\PathRepository' => '?',
            'App\\Repository\\Extra\\RefreshTokenRepository' => '?',
            'App\\Repository\\Extra\\RoleRepository' => '?',
            'App\\Repository\\Extra\\UserOtpRepository' => '?',
        ])));

        return $container->privates['doctrine.orm.default_configuration'] = $instance;
    }
}
