<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Dashboard\DashboardController' shared autowired service.
     *
     * @return \App\Controller\Dashboard\DashboardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Dashboard/DashboardController.php';
        include_once \dirname(__DIR__, 4).'/src/Manager/Admin/DashboardManager.php';

        $instance = new \App\Controller\Dashboard\DashboardController(new \App\Manager\Admin\DashboardManager(($container->privates['App\\Repository\\CompanyRepository'] ?? $container->load('getCompanyRepository2Service')), ($container->privates['App\\Repository\\CreditRequestRepository'] ?? $container->load('getCreditRequestRepositoryService')), ($container->privates['App\\Repository\\Admin\\AuditLogRepository'] ?? $container->load('getAuditLogRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Dashboard\\DashboardController', $container));

        return $container->services['App\\Controller\\Dashboard\\DashboardController'] = $instance;
    }
}
