<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeneralSettingControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Extra\GeneralSettingController' shared autowired service.
     *
     * @return \App\Controller\Extra\GeneralSettingController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Extra/GeneralSettingController.php';
        include_once \dirname(__DIR__, 4).'/src/Manager/Extra/GeneralSettingManager.php';
        include_once \dirname(__DIR__, 4).'/src/Manager/Extra/NotificationSettingManager.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        $instance = new \App\Controller\Extra\GeneralSettingController(new \App\Manager\Extra\GeneralSettingManager($a, ($container->privates['App\\Repository\\Extra\\GeneralSettingRepository'] ?? $container->load('getGeneralSettingRepositoryService')), ($container->privates['App\\Repository\\Extra\\GeneralSettingHistoryRepository'] ?? $container->load('getGeneralSettingHistoryRepositoryService'))), new \App\Manager\Extra\NotificationSettingManager($a, ($container->privates['App\\Repository\\Extra\\NotificationSettingRepository'] ?? $container->load('getNotificationSettingRepositoryService')), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Extra\\GeneralSettingController', $container));

        return $container->services['App\\Controller\\Extra\\GeneralSettingController'] = $instance;
    }
}
