<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Events\LoginSubscriber' shared autowired service.
     *
     * @return \App\Events\LoginSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Events/LoginSubscriber.php';

        return $container->privates['App\\Events\\LoginSubscriber'] = new \App\Events\LoginSubscriber(($container->privates['App\\Repository\\Admin\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
