<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\NotificationService' shared autowired service.
     *
     * @return \App\Service\NotificationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/NotificationService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/FcmPushService.php';

        return $container->privates['App\\Service\\NotificationService'] = new \App\Service\NotificationService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\Admin\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\Extra\\NotificationRepository'] ?? $container->load('getNotificationRepositoryService')), new \App\Service\FcmPushService(($container->privates['logger'] ?? self::getLoggerService($container))));
    }
}
