<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPassengerManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Manager\Business\PassengerManager' shared autowired service.
     *
     * @return \App\Manager\Business\PassengerManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Manager/Business/PassengerManager.php';

        return $container->privates['App\\Manager\\Business\\PassengerManager'] = new \App\Manager\Business\PassengerManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\Business\\PassengerRepository'] ?? $container->load('getPassengerRepositoryService')), ($container->privates['App\\Repository\\Admin\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->privates['App\\Service\\NotificationService'] ?? $container->load('getNotificationServiceService')), ($container->privates['App\\Repository\\Extra\\NotificationRepository'] ?? $container->load('getNotificationRepositoryService')));
    }
}
