<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublicReferentialControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PublicReferentialController' shared autowired service.
     *
     * @return \App\Controller\PublicReferentialController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PublicReferentialController.php';

        $instance = new \App\Controller\PublicReferentialController(($container->privates['App\\Repository\\Business\\CompanyRepository'] ?? $container->load('getCompanyRepositoryService')), ($container->privates['App\\Repository\\Business\\RouteRepository'] ?? $container->load('getRouteRepositoryService')), ($container->privates['App\\Repository\\Business\\TariffRepository'] ?? $container->load('getTariffRepositoryService')), ($container->privates['App\\Repository\\Business\\CityRepository'] ?? $container->load('getCityRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\PublicReferentialController', $container));

        return $container->services['App\\Controller\\PublicReferentialController'] = $instance;
    }
}
