<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyncMenuPathsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\SyncMenuPathsCommand' shared autowired service.
     *
     * @return \App\Command\SyncMenuPathsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/SyncMenuPathsCommand.php';

        $instance = new \App\Command\SyncMenuPathsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\Extra\\PathRepository'] ?? $container->load('getPathRepositoryService')), ($container->privates['App\\Repository\\Extra\\RoleRepository'] ?? $container->load('getRoleRepositoryService')));

        $instance->setName('z:g:sync:menu-paths');
        $instance->setDescription('Synchroniser');

        return $container->privates['App\\Command\\SyncMenuPathsCommand'] = $instance;
    }
}
