<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSharedManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Manager\Extra\SharedManager' shared autowired service.
     *
     * @return \App\Manager\Extra\SharedManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Manager/Extra/SharedManager.php';
        include_once \dirname(__DIR__, 4).'/src/Utils/TypeVariable.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        if (isset($container->privates['App\\Manager\\Extra\\SharedManager'])) {
            return $container->privates['App\\Manager\\Extra\\SharedManager'];
        }

        $instance = new \App\Manager\Extra\SharedManager($a, ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), new \App\Utils\TypeVariable());

        if (isset($container->privates['App\\Manager\\Extra\\SharedManager'])) {
            return $container->privates['App\\Manager\\Extra\\SharedManager'];
        }

        return $container->privates['App\\Manager\\Extra\\SharedManager'] = $instance;
    }
}
