<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyncAdminRoutesCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\SyncAdminRoutesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\SyncAdminRoutesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('z:g:sync:admin-routes', [], 'Synchronise les nouvelles routes avec le rôle super administrateur existant.', false, #[\Closure(name: 'App\\Command\\SyncAdminRoutesCommand')] fn (): \App\Command\SyncAdminRoutesCommand => ($container->privates['App\\Command\\SyncAdminRoutesCommand'] ?? $container->load('getSyncAdminRoutesCommandService')));
    }
}
