<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Business\StationController' shared autowired service.
     *
     * @return \App\Controller\Business\StationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Business/StationController.php';
        include_once \dirname(__DIR__, 4).'/src/Manager/Business/StationManager.php';

        $instance = new \App\Controller\Business\StationController(new \App\Manager\Business\StationManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\Business\\StationRepository'] ?? $container->load('getStationRepositoryService')), ($container->privates['App\\Repository\\Business\\CityRepository'] ?? $container->load('getCityRepositoryService')), ($container->privates['App\\Repository\\Business\\CompanyRepository'] ?? $container->load('getCompanyRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Business\\StationController', $container));

        return $container->services['App\\Controller\\Business\\StationController'] = $instance;
    }
}
