<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSharedControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Extra\SharedController' shared autowired service.
     *
     * @return \App\Controller\Extra\SharedController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Extra/SharedController.php';

        $instance = new \App\Controller\Extra\SharedController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Extra\\SharedController', $container));

        return $container->services['App\\Controller\\Extra\\SharedController'] = $instance;
    }
}
