<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyncMenuPathsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\SyncMenuPathsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\SyncMenuPathsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('z:g:sync:menu-paths', [], 'Synchroniser', false, #[\Closure(name: 'App\\Command\\SyncMenuPathsCommand')] fn (): \App\Command\SyncMenuPathsCommand => ($container->privates['App\\Command\\SyncMenuPathsCommand'] ?? $container->load('getSyncMenuPathsCommandService')));
    }
}
