<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTariffControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Business\TariffController' shared autowired service.
     *
     * @return \App\Controller\Business\TariffController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Business/TariffController.php';
        include_once \dirname(__DIR__, 4).'/src/Manager/Business/TariffManager.php';

        $instance = new \App\Controller\Business\TariffController(new \App\Manager\Business\TariffManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\Business\\TariffRepository'] ?? $container->load('getTariffRepositoryService')), ($container->privates['App\\Repository\\Business\\RouteRepository'] ?? $container->load('getRouteRepositoryService')), ($container->privates['App\\Repository\\Business\\CompanyRepository'] ?? $container->load('getCompanyRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Business\\TariffController', $container));

        return $container->services['App\\Controller\\Business\\TariffController'] = $instance;
    }
}
