<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateEntityUuidsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\UpdateEntityUuidsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\UpdateEntityUuidsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:update-uuids', [], 'Génère et met à jour les UUID manquants pour les compagnies, gares, agents et passagers.', false, #[\Closure(name: 'App\\Command\\UpdateEntityUuidsCommand')] fn (): \App\Command\UpdateEntityUuidsCommand => ($container->privates['App\\Command\\UpdateEntityUuidsCommand'] ?? $container->load('getUpdateEntityUuidsCommandService')));
    }
}
