<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserDBProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\UserDBProvider' shared autowired service.
     *
     * @return \App\Security\UserDBProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Security/UserDBProvider.php';

        return $container->privates['App\\Security\\UserDBProvider'] = new \App\Security\UserDBProvider(($container->privates['App\\Repository\\Admin\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
