<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUploaderControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Extra\UploaderController' shared autowired service.
     *
     * @return \App\Controller\Extra\UploaderController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Extra/UploaderController.php';
        include_once \dirname(__DIR__, 4).'/src/Manager/Extra/UploaderManager.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        $instance = new \App\Controller\Extra\UploaderController($a, new \App\Manager\Extra\UploaderManager($a, ($container->privates['App\\Repository\\Extra\\FolderRepository'] ?? $container->load('getFolderRepositoryService')), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->privates['App\\Repository\\Admin\\UserRepository'] ?? $container->load('getUserRepositoryService'))), ($container->privates['App\\Repository\\Extra\\FileRepository'] ?? $container->load('getFileRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Extra\\UploaderController', $container));

        return $container->services['App\\Controller\\Extra\\UploaderController'] = $instance;
    }
}
