<?php

namespace ContainerMulH2wG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateEntityUuidsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\UpdateEntityUuidsCommand' shared autowired service.
     *
     * @return \App\Command\UpdateEntityUuidsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/UpdateEntityUuidsCommand.php';

        $instance = new \App\Command\UpdateEntityUuidsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('app:update-uuids');
        $instance->setDescription('Génère et met à jour les UUID manquants pour les compagnies, gares, agents et passagers.');

        return $container->privates['App\\Command\\UpdateEntityUuidsCommand'] = $instance;
    }
}
