<?php

namespace Proxies\__CG__\App\Entity\Business;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Station extends \App\Entity\Business\Station implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'deletedAt' => [parent::class, 'deletedAt', null, 8],
        "\0".'*'."\0".'searchableDetail' => [parent::class, 'searchableDetail', null, 8],
        "\0".'*'."\0".'searchableTitle' => [parent::class, 'searchableTitle', null, 8],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null, 16],
        "\0".parent::class."\0".'code' => [parent::class, 'code', null, 16],
        "\0".parent::class."\0".'company' => [parent::class, 'company', null, 16],
        "\0".parent::class."\0".'createBy' => [parent::class, 'createBy', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'removeBy' => [parent::class, 'removeBy', null, 16],
        "\0".parent::class."\0".'updateBy' => [parent::class, 'updateBy', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'uuid' => [parent::class, 'uuid', null, 16],
        'city' => [parent::class, 'city', null, 16],
        'code' => [parent::class, 'code', null, 16],
        'company' => [parent::class, 'company', null, 16],
        'createBy' => [parent::class, 'createBy', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'deletedAt' => [parent::class, 'deletedAt', null, 8],
        'id' => [parent::class, 'id', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'removeBy' => [parent::class, 'removeBy', null, 16],
        'searchableDetail' => [parent::class, 'searchableDetail', null, 8],
        'searchableTitle' => [parent::class, 'searchableTitle', null, 8],
        'updateBy' => [parent::class, 'updateBy', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'uuid' => [parent::class, 'uuid', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
