<?php

namespace Proxies\__CG__\App\Entity\Admin;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\Admin\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'deletedAt' => [parent::class, 'deletedAt', null, 8],
        "\0".'*'."\0".'searchableDetail' => [parent::class, 'searchableDetail', null, 8],
        "\0".'*'."\0".'searchableTitle' => [parent::class, 'searchableTitle', null, 8],
        "\0".parent::class."\0".'agent' => [parent::class, 'agent', null, 16],
        "\0".parent::class."\0".'avatar' => [parent::class, 'avatar', null, 16],
        "\0".parent::class."\0".'code' => [parent::class, 'code', null, 16],
        "\0".parent::class."\0".'createBy' => [parent::class, 'createBy', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'droits' => [parent::class, 'droits', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'fcmToken' => [parent::class, 'fcmToken', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isEnabled' => [parent::class, 'isEnabled', null, 16],
        "\0".parent::class."\0".'isFirst' => [parent::class, 'isFirst', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'passenger' => [parent::class, 'passenger', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'removeBy' => [parent::class, 'removeBy', null, 16],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null, 16],
        "\0".parent::class."\0".'station' => [parent::class, 'station', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'updateBy' => [parent::class, 'updateBy', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null, 16],
        "\0".parent::class."\0".'uuid' => [parent::class, 'uuid', null, 16],
        'agent' => [parent::class, 'agent', null, 16],
        'avatar' => [parent::class, 'avatar', null, 16],
        'code' => [parent::class, 'code', null, 16],
        'createBy' => [parent::class, 'createBy', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'deletedAt' => [parent::class, 'deletedAt', null, 8],
        'droits' => [parent::class, 'droits', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'fcmToken' => [parent::class, 'fcmToken', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isEnabled' => [parent::class, 'isEnabled', null, 16],
        'isFirst' => [parent::class, 'isFirst', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'passenger' => [parent::class, 'passenger', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'removeBy' => [parent::class, 'removeBy', null, 16],
        'roles' => [parent::class, 'roles', null, 16],
        'searchableDetail' => [parent::class, 'searchableDetail', null, 8],
        'searchableTitle' => [parent::class, 'searchableTitle', null, 8],
        'station' => [parent::class, 'station', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'updateBy' => [parent::class, 'updateBy', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'username' => [parent::class, 'username', null, 16],
        'uuid' => [parent::class, 'uuid', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
