<?php

namespace Proxies\__CG__\App\Entity\Business;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Agent extends \App\Entity\Business\Agent implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'deletedAt' => [parent::class, 'deletedAt', null, 8],
        "\0".'*'."\0".'searchableDetail' => [parent::class, 'searchableDetail', null, 8],
        "\0".'*'."\0".'searchableTitle' => [parent::class, 'searchableTitle', null, 8],
        "\0".parent::class."\0".'agentCode' => [parent::class, 'agentCode', null, 16],
        "\0".parent::class."\0".'code' => [parent::class, 'code', null, 16],
        "\0".parent::class."\0".'company' => [parent::class, 'company', null, 16],
        "\0".parent::class."\0".'countryCode' => [parent::class, 'countryCode', null, 16],
        "\0".parent::class."\0".'createBy' => [parent::class, 'createBy', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'fcmToken' => [parent::class, 'fcmToken', null, 16],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null, 16],
        "\0".parent::class."\0".'gender' => [parent::class, 'gender', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isActivated' => [parent::class, 'isActivated', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null, 16],
        "\0".parent::class."\0".'phoneNumber' => [parent::class, 'phoneNumber', null, 16],
        "\0".parent::class."\0".'removeBy' => [parent::class, 'removeBy', null, 16],
        "\0".parent::class."\0".'residenceAddress' => [parent::class, 'residenceAddress', null, 16],
        "\0".parent::class."\0".'stationAssigned' => [parent::class, 'stationAssigned', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'updateBy' => [parent::class, 'updateBy', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        "\0".parent::class."\0".'uuid' => [parent::class, 'uuid', null, 16],
        'agentCode' => [parent::class, 'agentCode', null, 16],
        'code' => [parent::class, 'code', null, 16],
        'company' => [parent::class, 'company', null, 16],
        'countryCode' => [parent::class, 'countryCode', null, 16],
        'createBy' => [parent::class, 'createBy', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'deletedAt' => [parent::class, 'deletedAt', null, 8],
        'fcmToken' => [parent::class, 'fcmToken', null, 16],
        'firstname' => [parent::class, 'firstname', null, 16],
        'gender' => [parent::class, 'gender', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isActivated' => [parent::class, 'isActivated', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'lastname' => [parent::class, 'lastname', null, 16],
        'phoneNumber' => [parent::class, 'phoneNumber', null, 16],
        'removeBy' => [parent::class, 'removeBy', null, 16],
        'residenceAddress' => [parent::class, 'residenceAddress', null, 16],
        'searchableDetail' => [parent::class, 'searchableDetail', null, 8],
        'searchableTitle' => [parent::class, 'searchableTitle', null, 8],
        'stationAssigned' => [parent::class, 'stationAssigned', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'updateBy' => [parent::class, 'updateBy', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'user' => [parent::class, 'user', null, 16],
        'uuid' => [parent::class, 'uuid', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
