<?php

namespace Proxies\__CG__\App\Entity\Business;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Passenger extends \App\Entity\Business\Passenger implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'deletedAt' => [parent::class, 'deletedAt', null, 8],
        "\0".'*'."\0".'searchableDetail' => [parent::class, 'searchableDetail', null, 8],
        "\0".'*'."\0".'searchableTitle' => [parent::class, 'searchableTitle', null, 8],
        "\0".parent::class."\0".'availableCredit' => [parent::class, 'availableCredit', null, 16],
        "\0".parent::class."\0".'code' => [parent::class, 'code', null, 16],
        "\0".parent::class."\0".'contacts' => [parent::class, 'contacts', null, 16],
        "\0".parent::class."\0".'countryCode' => [parent::class, 'countryCode', null, 16],
        "\0".parent::class."\0".'createBy' => [parent::class, 'createBy', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'creditRequests' => [parent::class, 'creditRequests', null, 16],
        "\0".parent::class."\0".'creditScore' => [parent::class, 'creditScore', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'fcmToken' => [parent::class, 'fcmToken', null, 16],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null, 16],
        "\0".parent::class."\0".'gender' => [parent::class, 'gender', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'identityCardNumber' => [parent::class, 'identityCardNumber', null, 16],
        "\0".parent::class."\0".'identityRectoUrl' => [parent::class, 'identityRectoUrl', null, 16],
        "\0".parent::class."\0".'identityStatus' => [parent::class, 'identityStatus', null, 16],
        "\0".parent::class."\0".'identityType' => [parent::class, 'identityType', null, 16],
        "\0".parent::class."\0".'identityVersoUrl' => [parent::class, 'identityVersoUrl', null, 16],
        "\0".parent::class."\0".'isBlacklisted' => [parent::class, 'isBlacklisted', null, 16],
        "\0".parent::class."\0".'isIdentified' => [parent::class, 'isIdentified', null, 16],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null, 16],
        "\0".parent::class."\0".'maxCreditLimit' => [parent::class, 'maxCreditLimit', null, 16],
        "\0".parent::class."\0".'phoneNumber' => [parent::class, 'phoneNumber', null, 16],
        "\0".parent::class."\0".'pinCode' => [parent::class, 'pinCode', null, 16],
        "\0".parent::class."\0".'profileType' => [parent::class, 'profileType', null, 16],
        "\0".parent::class."\0".'removeBy' => [parent::class, 'removeBy', null, 16],
        "\0".parent::class."\0".'residenceAddress' => [parent::class, 'residenceAddress', null, 16],
        "\0".parent::class."\0".'selfieUrl' => [parent::class, 'selfieUrl', null, 16],
        "\0".parent::class."\0".'totalDebt' => [parent::class, 'totalDebt', null, 16],
        "\0".parent::class."\0".'totalReimbursed' => [parent::class, 'totalReimbursed', null, 16],
        "\0".parent::class."\0".'updateBy' => [parent::class, 'updateBy', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'uuid' => [parent::class, 'uuid', null, 16],
        'availableCredit' => [parent::class, 'availableCredit', null, 16],
        'code' => [parent::class, 'code', null, 16],
        'contacts' => [parent::class, 'contacts', null, 16],
        'countryCode' => [parent::class, 'countryCode', null, 16],
        'createBy' => [parent::class, 'createBy', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'creditRequests' => [parent::class, 'creditRequests', null, 16],
        'creditScore' => [parent::class, 'creditScore', null, 16],
        'deletedAt' => [parent::class, 'deletedAt', null, 8],
        'email' => [parent::class, 'email', null, 16],
        'fcmToken' => [parent::class, 'fcmToken', null, 16],
        'firstname' => [parent::class, 'firstname', null, 16],
        'gender' => [parent::class, 'gender', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'identityCardNumber' => [parent::class, 'identityCardNumber', null, 16],
        'identityRectoUrl' => [parent::class, 'identityRectoUrl', null, 16],
        'identityStatus' => [parent::class, 'identityStatus', null, 16],
        'identityType' => [parent::class, 'identityType', null, 16],
        'identityVersoUrl' => [parent::class, 'identityVersoUrl', null, 16],
        'isBlacklisted' => [parent::class, 'isBlacklisted', null, 16],
        'isIdentified' => [parent::class, 'isIdentified', null, 16],
        'lastname' => [parent::class, 'lastname', null, 16],
        'maxCreditLimit' => [parent::class, 'maxCreditLimit', null, 16],
        'phoneNumber' => [parent::class, 'phoneNumber', null, 16],
        'pinCode' => [parent::class, 'pinCode', null, 16],
        'profileType' => [parent::class, 'profileType', null, 16],
        'removeBy' => [parent::class, 'removeBy', null, 16],
        'residenceAddress' => [parent::class, 'residenceAddress', null, 16],
        'searchableDetail' => [parent::class, 'searchableDetail', null, 8],
        'searchableTitle' => [parent::class, 'searchableTitle', null, 8],
        'selfieUrl' => [parent::class, 'selfieUrl', null, 16],
        'totalDebt' => [parent::class, 'totalDebt', null, 16],
        'totalReimbursed' => [parent::class, 'totalReimbursed', null, 16],
        'updateBy' => [parent::class, 'updateBy', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'uuid' => [parent::class, 'uuid', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
