<?php

namespace Proxies\__CG__\App\Entity\Business;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Credit extends \App\Entity\Business\Credit implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'deletedAt' => [parent::class, 'deletedAt', null, 8],
        "\0".'*'."\0".'searchableDetail' => [parent::class, 'searchableDetail', null, 8],
        "\0".'*'."\0".'searchableTitle' => [parent::class, 'searchableTitle', null, 8],
        "\0".parent::class."\0".'amountRequested' => [parent::class, 'amountRequested', null, 16],
        "\0".parent::class."\0".'arrivalCity' => [parent::class, 'arrivalCity', null, 16],
        "\0".parent::class."\0".'code' => [parent::class, 'code', null, 16],
        "\0".parent::class."\0".'company' => [parent::class, 'company', null, 16],
        "\0".parent::class."\0".'createBy' => [parent::class, 'createBy', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'departureCity' => [parent::class, 'departureCity', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isRoundTrip' => [parent::class, 'isRoundTrip', null, 16],
        "\0".parent::class."\0".'passenger' => [parent::class, 'passenger', null, 16],
        "\0".parent::class."\0".'passengerCount' => [parent::class, 'passengerCount', null, 16],
        "\0".parent::class."\0".'rejectionReason' => [parent::class, 'rejectionReason', null, 16],
        "\0".parent::class."\0".'removeBy' => [parent::class, 'removeBy', null, 16],
        "\0".parent::class."\0".'repaidAmount' => [parent::class, 'repaidAmount', null, 16],
        "\0".parent::class."\0".'repaymentStatus' => [parent::class, 'repaymentStatus', null, 16],
        "\0".parent::class."\0".'returnDate' => [parent::class, 'returnDate', null, 16],
        "\0".parent::class."\0".'route' => [parent::class, 'route', null, 16],
        "\0".parent::class."\0".'serviceFee' => [parent::class, 'serviceFee', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'tickets' => [parent::class, 'tickets', null, 16],
        "\0".parent::class."\0".'totalAmount' => [parent::class, 'totalAmount', null, 16],
        "\0".parent::class."\0".'travelDate' => [parent::class, 'travelDate', null, 16],
        "\0".parent::class."\0".'unitPrice' => [parent::class, 'unitPrice', null, 16],
        "\0".parent::class."\0".'updateBy' => [parent::class, 'updateBy', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'uuid' => [parent::class, 'uuid', null, 16],
        'amountRequested' => [parent::class, 'amountRequested', null, 16],
        'arrivalCity' => [parent::class, 'arrivalCity', null, 16],
        'code' => [parent::class, 'code', null, 16],
        'company' => [parent::class, 'company', null, 16],
        'createBy' => [parent::class, 'createBy', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'deletedAt' => [parent::class, 'deletedAt', null, 8],
        'departureCity' => [parent::class, 'departureCity', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isRoundTrip' => [parent::class, 'isRoundTrip', null, 16],
        'passenger' => [parent::class, 'passenger', null, 16],
        'passengerCount' => [parent::class, 'passengerCount', null, 16],
        'rejectionReason' => [parent::class, 'rejectionReason', null, 16],
        'removeBy' => [parent::class, 'removeBy', null, 16],
        'repaidAmount' => [parent::class, 'repaidAmount', null, 16],
        'repaymentStatus' => [parent::class, 'repaymentStatus', null, 16],
        'returnDate' => [parent::class, 'returnDate', null, 16],
        'route' => [parent::class, 'route', null, 16],
        'searchableDetail' => [parent::class, 'searchableDetail', null, 8],
        'searchableTitle' => [parent::class, 'searchableTitle', null, 8],
        'serviceFee' => [parent::class, 'serviceFee', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'tickets' => [parent::class, 'tickets', null, 16],
        'totalAmount' => [parent::class, 'totalAmount', null, 16],
        'travelDate' => [parent::class, 'travelDate', null, 16],
        'unitPrice' => [parent::class, 'unitPrice', null, 16],
        'updateBy' => [parent::class, 'updateBy', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'uuid' => [parent::class, 'uuid', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
