<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H89vWvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._H89vWv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Extra\\SharedController::index' => ['privates', '.service_locator.Xwne7t5.App\\Controller\\Extra\\SharedController::index()', 'getSharedControllerindexService', true],
            'App\\Controller\\Security\\SecurityController::refreshTokenAction' => ['privates', '.service_locator.DYr0wyw.App\\Controller\\Security\\SecurityController::refreshTokenAction()', 'getSecurityControllerrefreshTokenActionService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Extra\\SharedController:index' => ['privates', '.service_locator.Xwne7t5.App\\Controller\\Extra\\SharedController::index()', 'getSharedControllerindexService', true],
            'App\\Controller\\Security\\SecurityController:refreshTokenAction' => ['privates', '.service_locator.DYr0wyw.App\\Controller\\Security\\SecurityController::refreshTokenAction()', 'getSecurityControllerrefreshTokenActionService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Extra\\SharedController::index' => '?',
            'App\\Controller\\Security\\SecurityController::refreshTokenAction' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Extra\\SharedController:index' => '?',
            'App\\Controller\\Security\\SecurityController:refreshTokenAction' => '?',
        ]);

        if (isset($container->privates['.service_locator._H89vWv'])) {
            return $container->privates['.service_locator._H89vWv'];
        }

        return $container->privates['.service_locator._H89vWv'] = $instance;
    }
}
