<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreditControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Business\CreditController' shared autowired service.
     *
     * @return \App\Controller\Business\CreditController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Business/CreditController.php';
        include_once \dirname(__DIR__, 4).'/src/Manager/Business/CreditManager.php';

        $instance = new \App\Controller\Business\CreditController(new \App\Manager\Business\CreditManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\Business\\CreditRepository'] ?? $container->load('getCreditRepositoryService')), ($container->privates['App\\Repository\\Business\\PassengerRepository'] ?? $container->load('getPassengerRepositoryService')), ($container->privates['App\\Repository\\CompanyRepository'] ?? $container->load('getCompanyRepository2Service')), ($container->privates['App\\Service\\QrCodeService'] ?? $container->load('getQrCodeServiceService')), ($container->privates['App\\Service\\NotificationService'] ?? $container->load('getNotificationServiceService'))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Business\\CreditController', $container));

        return $container->services['App\\Controller\\Business\\CreditController'] = $instance;
    }
}
