<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompanyControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Business\CompanyController' shared autowired service.
     *
     * @return \App\Controller\Business\CompanyController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Business/CompanyController.php';
        include_once \dirname(__DIR__, 4).'/src/Manager/Business/CompanyManager.php';

        $instance = new \App\Controller\Business\CompanyController(new \App\Manager\Business\CompanyManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\Business\\CompanyRepository'] ?? $container->load('getCompanyRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Business\\CompanyController', $container));

        return $container->services['App\\Controller\\Business\\CompanyController'] = $instance;
    }
}
