<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandPathService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CommandPath' shared autowired service.
     *
     * @return \App\Command\CommandPath
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CommandPath.php';

        $instance = new \App\Command\CommandPath(($container->services['router'] ?? self::getRouterService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\Extra\\PathRepository'] ?? $container->load('getPathRepositoryService')));

        $instance->setName('z:g:path');
        $instance->setDescription('Generate path routes for Passe Voyage');

        return $container->privates['App\\Command\\CommandPath'] = $instance;
    }
}
