<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreditRequestPrinterControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Printer\CreditRequestPrinterController' shared autowired service.
     *
     * @return \App\Controller\Printer\CreditRequestPrinterController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Printer/CreditRequestPrinterController.php';

        $instance = new \App\Controller\Printer\CreditRequestPrinterController(($container->privates['App\\Repository\\CreditRequestRepository'] ?? $container->load('getCreditRequestRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Printer\\CreditRequestPrinterController', $container));

        return $container->services['App\\Controller\\Printer\\CreditRequestPrinterController'] = $instance;
    }
}
