<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublicAgentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PublicAgentController' shared autowired service.
     *
     * @return \App\Controller\PublicAgentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PublicAgentController.php';

        $instance = new \App\Controller\PublicAgentController(($container->privates['App\\Manager\\Business\\AgentManager'] ?? $container->load('getAgentManagerService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\PublicAgentController', $container));

        return $container->services['App\\Controller\\PublicAgentController'] = $instance;
    }
}
