<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPassengerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Business\PassengerController' shared autowired service.
     *
     * @return \App\Controller\Business\PassengerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Business/PassengerController.php';

        $instance = new \App\Controller\Business\PassengerController(($container->privates['App\\Repository\\Business\\PassengerRepository'] ?? $container->load('getPassengerRepositoryService')), ($container->privates['App\\Manager\\Business\\PassengerManager'] ?? $container->load('getPassengerManagerService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Business\\PassengerController', $container));

        return $container->services['App\\Controller\\Business\\PassengerController'] = $instance;
    }
}
