<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRouteControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Business\RouteController' shared autowired service.
     *
     * @return \App\Controller\Business\RouteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Business/RouteController.php';
        include_once \dirname(__DIR__, 4).'/src/Manager/Business/RouteManager.php';

        $instance = new \App\Controller\Business\RouteController(new \App\Manager\Business\RouteManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\Business\\RouteRepository'] ?? $container->load('getRouteRepositoryService')), ($container->privates['App\\Repository\\Business\\CityRepository'] ?? $container->load('getCityRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Business\\RouteController', $container));

        return $container->services['App\\Controller\\Business\\RouteController'] = $instance;
    }
}
