<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoleControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\RoleController' shared autowired service.
     *
     * @return \App\Controller\Admin\RoleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/RoleController.php';
        include_once \dirname(__DIR__, 4).'/src/Manager/Extra/RoleManager.php';

        $a = ($container->privates['App\\Repository\\Extra\\RoleRepository'] ?? $container->load('getRoleRepositoryService'));

        $instance = new \App\Controller\Admin\RoleController($a, new \App\Manager\Extra\RoleManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\Extra\\PathRepository'] ?? $container->load('getPathRepositoryService')), ($container->privates['App\\Repository\\Admin\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), $a));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Admin\\RoleController', $container));

        return $container->services['App\\Controller\\Admin\\RoleController'] = $instance;
    }
}
