<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyncAdminRoutesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\SyncAdminRoutesCommand' shared autowired service.
     *
     * @return \App\Command\SyncAdminRoutesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/SyncAdminRoutesCommand.php';

        $instance = new \App\Command\SyncAdminRoutesCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\Extra\\PathRepository'] ?? $container->load('getPathRepositoryService')), ($container->privates['App\\Repository\\Extra\\RoleRepository'] ?? $container->load('getRoleRepositoryService')));

        $instance->setName('z:g:sync:admin-routes');
        $instance->setDescription('Synchronise les nouvelles routes avec le rôle super administrateur existant.');

        return $container->privates['App\\Command\\SyncAdminRoutesCommand'] = $instance;
    }
}
