<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSharedControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xwne7t5.App\Controller\Extra\SharedController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'manager' => ['privates', 'App\\Manager\\Extra\\SharedManager', 'getSharedManagerService', true],
        ], [
            'manager' => 'App\\Manager\\Extra\\SharedManager',
        ]))->withContext('App\\Controller\\Extra\\SharedController::index()', $container);

        if (isset($container->privates['.service_locator.Xwne7t5.App\\Controller\\Extra\\SharedController::index()'])) {
            return $container->privates['.service_locator.Xwne7t5.App\\Controller\\Extra\\SharedController::index()'];
        }

        return $container->privates['.service_locator.Xwne7t5.App\\Controller\\Extra\\SharedController::index()'] = $instance;
    }
}
