<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Security\SecurityController' shared autowired service.
     *
     * @return \App\Controller\Security\SecurityController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Security/SecurityController.php';
        include_once \dirname(__DIR__, 4).'/src/Manager/Security/SecurityManager.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));
        $b = ($container->privates['App\\Repository\\Extra\\RefreshTokenRepository'] ?? $container->load('getRefreshTokenRepositoryService'));

        $instance = new \App\Controller\Security\SecurityController($a, new \App\Manager\Security\SecurityManager($a, ($container->privates['App\\Repository\\Admin\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')), $b, ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container))), $b);

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Security\\SecurityController', $container));

        return $container->services['App\\Controller\\Security\\SecurityController'] = $instance;
    }
}
