<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllerrefreshTokenActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DYr0wyw.App\Controller\Security\SecurityController::refreshTokenAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'jwtManager' => ['services', 'lexik_jwt_authentication.jwt_manager', 'getLexikJwtAuthentication_JwtManagerService', true],
        ], [
            'jwtManager' => '?',
        ]))->withContext('App\\Controller\\Security\\SecurityController::refreshTokenAction()', $container);

        if (isset($container->privates['.service_locator.DYr0wyw.App\\Controller\\Security\\SecurityController::refreshTokenAction()'])) {
            return $container->privates['.service_locator.DYr0wyw.App\\Controller\\Security\\SecurityController::refreshTokenAction()'];
        }

        return $container->privates['.service_locator.DYr0wyw.App\\Controller\\Security\\SecurityController::refreshTokenAction()'] = $instance;
    }
}
