<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Config_ApiForgotService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.firewall.map.config.api_forgot' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/FirewallConfig.php';

        return $container->privates['security.firewall.map.config.api_forgot'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('api_forgot', 'security.user_checker', '.security.request_matcher.ErTMGRi', true, true, 'App\\Security\\UserDBProvider', NULL, NULL, NULL, NULL, [], NULL, NULL);
    }
}
