<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTicketControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Business\TicketController' shared autowired service.
     *
     * @return \App\Controller\Business\TicketController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Business/TicketController.php';
        include_once \dirname(__DIR__, 4).'/src/Manager/Business/TicketManager.php';

        $instance = new \App\Controller\Business\TicketController(new \App\Manager\Business\TicketManager(($container->privates['App\\Repository\\Business\\TicketRepository'] ?? $container->load('getTicketRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\QrCodeService'] ?? $container->load('getQrCodeServiceService'))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Business\\TicketController', $container));

        return $container->services['App\\Controller\\Business\\TicketController'] = $instance;
    }
}
