<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\UserController' shared autowired service.
     *
     * @return \App\Controller\Admin\UserController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/UserController.php';
        include_once \dirname(__DIR__, 4).'/src/Manager/Admin/UserManager.php';

        $a = ($container->privates['App\\Repository\\Admin\\UserRepository'] ?? $container->load('getUserRepositoryService'));
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        $instance = new \App\Controller\Admin\UserController($a, new \App\Manager\Admin\UserManager($b, $a, ($container->privates['App\\Repository\\Extra\\RoleRepository'] ?? $container->load('getRoleRepositoryService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService'))), $b);

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Admin\\UserController', $container));

        return $container->services['App\\Controller\\Admin\\UserController'] = $instance;
    }
}
