<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUuidEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Events\UuidEvent' shared autowired service.
     *
     * @return \App\Events\UuidEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/event-manager/src/EventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/EventSubscriber/EventSubscriberInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Events/UuidEvent.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        if (isset($container->privates['App\\Events\\UuidEvent'])) {
            return $container->privates['App\\Events\\UuidEvent'];
        }
        $b = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Events\\UuidEvent'])) {
            return $container->privates['App\\Events\\UuidEvent'];
        }

        $instance = new \App\Events\UuidEvent($a, $b);

        if (isset($container->privates['App\\Events\\UuidEvent'])) {
            return $container->privates['App\\Events\\UuidEvent'];
        }

        return $container->privates['App\\Events\\UuidEvent'] = $instance;
    }
}
