<?php

namespace ContainerArnA9xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Events\UserEvent' shared autowired service.
     *
     * @return \App\Events\UserEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/event-manager/src/EventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/EventSubscriber/EventSubscriberInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Events/UserEvent.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Events\\UserEvent'])) {
            return $container->privates['App\\Events\\UserEvent'];
        }

        $instance = new \App\Events\UserEvent($a);

        if (isset($container->privates['App\\Events\\UserEvent'])) {
            return $container->privates['App\\Events\\UserEvent'];
        }

        return $container->privates['App\\Events\\UserEvent'] = $instance;
    }
}
