<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMulH2wG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMulH2wG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMulH2wG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMulH2wG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMulH2wG\App_KernelDevDebugContainer([
    'container.build_hash' => 'MulH2wG',
    'container.build_id' => '41d49692',
    'container.build_time' => 1787338147,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMulH2wG');
