<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHmgpaau\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHmgpaau/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHmgpaau.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHmgpaau\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHmgpaau\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hmgpaau',
    'container.build_id' => '42a4df2e',
    'container.build_time' => 1787434310,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHmgpaau');
