<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEkjbvQM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEkjbvQM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEkjbvQM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEkjbvQM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEkjbvQM\App_KernelDevDebugContainer([
    'container.build_hash' => 'EkjbvQM',
    'container.build_id' => '1c5b0472',
    'container.build_time' => 1788722655,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEkjbvQM');
